// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;
using MySqlConnector;
using CorsovaiBD.Models;

namespace CorsovaiBD
{
    public partial class LoginForm : NSViewController
    {
        public LoginForm(IntPtr handle) : base(handle)
        {
        }

        partial void registrationFormButton(NSObject sender)
        {
            var viewController = this.Storyboard.InstantiateControllerWithIdentifier("RegistrationForm") as NSViewController;
            if (viewController != null)
            {
                PresentViewControllerAsModalWindow(viewController);
                this.View.Window.Close();
                // Close the current window
            }
        }
        private bool areInputsNone(string username, string password)
        {
            if (username == "" && password == "")
            {
                var alert = new NSAlert
                {
                    AlertStyle = NSAlertStyle.Critical,
                    InformativeText = "Username and Password must be set",
                    MessageText = "Username and Password are none"
                };
                alert.RunModal();
                return true;
            }
            if (username == "")
            {
                var alert = new NSAlert
                {
                    AlertStyle = NSAlertStyle.Critical,
                    InformativeText = "Username must be set",
                    MessageText = "Login Failed"
                };
                alert.RunModal();
                return true;
            }
            if (password == "")
            {
                var alert = new NSAlert
                {
                    AlertStyle = NSAlertStyle.Critical,
                    InformativeText = "Password must be set",
                    MessageText = "Login Failed"
                };
                alert.RunModal();
                return true;
            }
            return false;
        }
        partial void loginButton(NSObject sender)
        {
            // Perform login logic here
            var username = usernameField.StringValue;
            var password = passwordField.StringValue;
            if (areInputsNone(username, password))
            {
                return;
            };

            string query = $"SELECT * FROM Users WHERE username = @username AND password = @password";

            // Create a MySqlCommand object with the query and the connection
            using (MySqlConnection connection = new MySqlConnection(((AppDelegate)NSApplication.SharedApplication.Delegate).connectionString)){ 
                connection.Open();
                using (MySqlCommand command = new MySqlCommand(query, connection)) { 
                    // Add the parameters to the command
                    command.Parameters.AddWithValue("@username", username);
                    command.Parameters.AddWithValue("@password", password);

                    // Execute the query and get the result
                    MySqlDataReader reader = command.ExecuteReader();

                    try
                    {
                        reader.Read();
                        // Login successful
                        // Open the main view controller or perform any other actions
                        // username is correct so i dont need to get it from db
                        bool isAdmin = reader.GetBoolean("isAdmin");
                        var currentUser = new User(username, isAdmin);
                        ((AppDelegate)NSApplication.SharedApplication.Delegate).currentUser = currentUser;
                        var mainController = this.Storyboard.InstantiateControllerWithIdentifier("MainController") as NSViewController;
                        if (mainController != null)
                        {
                            PresentViewControllerAsModalWindow(mainController);
                            this.View.Window.Close();
                            // Close the current window
                        }
                    }
                    catch
                    {
                        // Login failed n
                        NSAlert alert = new NSAlert
                        {
                            AlertStyle = NSAlertStyle.Critical,
                            InformativeText = "Invalid username or password",
                            MessageText = "Login Failed"
                        };
                        alert.RunModal();
                    }
                }
            }
        }

        partial void exitButton(NSObject sender)
        {
            this.View.Window.Close();
        }

    }
}

