// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace CorsovaiBD
{
	public partial class RegistationForm : NSViewController
	{
		public RegistationForm (IntPtr handle) : base (handle)
		{
		}
	}
}
