// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace CorsovaiBD
{
	public partial class LoginForm : NSViewController
	{
		public LoginForm (IntPtr handle) : base (handle)
		{
		}
	}
}
